#spring.application.name=api-gateway-service
#server.port=8000
#
#
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
#
#spring.cloud.gateway.discovery.locator.enabled=false
#spring.cloud.netflix.eureka.discovery.enabled=true
#
## --- Route Configuration ---
#
## 1. Product Service Route
#spring.cloud.gateway.routes[0].id=product-service
##  lb://PRODUCT-SERVICE
#spring.cloud.gateway.routes[0].uri=lb://PRODUCT-SERVICE
#spring.cloud.gateway.routes[0].predicates[0]=Path=/api/products/**
#
## 2. Order Service Route
#spring.cloud.gateway.routes[1].id=order-service
##  lb://ORDER-SERVICE
#spring.cloud.gateway.routes[1].uri=lb://ORDER-SERVICE
#spring.cloud.gateway.routes[1].predicates[0]=Path=/api/orders/**

spring.application.name=api-gateway-service
server.port=8000

#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Enable discovery and automatic route generation to help us test
spring.cloud.gateway.discovery.locator.enabled=true
#spring.cloud.netflix.eureka.discovery.enabled=true
#
## --- Manual Route Configuration ---
#
## 1. Product Service Route
#spring.cloud.gateway.routes[0].id=product-service
#spring.cloud.gateway.routes[0].uri=lb://PRODUCT-SERVICE
#spring.cloud.gateway.routes[0].predicates[0]=Path=/api/products/**
#
## 2. Order Service Route
#spring.cloud.gateway.routes[1].id=order-service
#spring.cloud.gateway.routes[1].uri=lb://ORDER-SERVICE
#spring.cloud.gateway.routes[1].predicates[0]=Path=/api/orders/**